services:
  db:
    image: postgres:16
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - .env
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
    command: ["python", "src/manage.py", "runserver", "0.0.0.0:8000"]

volumes:
  db-data:
  static_volume:
