# Generated by Django 5.2.3 on 2025-06-15 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('document', models.CharField(max_length=14, verbose_name='CPF/CNPJ')),
            ],
        ),
        migrations.CreateModel(
            name='Harvest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.SmallIntegerField(verbose_name='Ano')),
            ],
        ),
        migrations.CreateModel(
            name='CultivatedCrop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('harvest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agriculture_api.harvest', verbose_name='Safra')),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('city', models.CharField(max_length=255, verbose_name='Cidade')),
                ('state', models.CharField(max_length=255, verbose_name='Estado')),
                ('total_area', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Área Total')),
                ('arable_area', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Área Agricultável')),
                ('vegetation_area', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Área de Vegetação')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agriculture_api.farmer', verbose_name='Fazendeiro')),
            ],
        ),
        migrations.CreateModel(
            name='CropInProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cultivated_crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agriculture_api.cultivatedcrop', verbose_name='Cultura')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agriculture_api.property', verbose_name='Propriedade')),
            ],
        ),
    ]
