# Generated by Django 5.2.3 on 2025-06-16 14:43

import agriculture_api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriculture_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='document',
            field=models.CharField(max_length=14, unique=True, validators=[agriculture_api.validators.validate_document], verbose_name='CPF/CNPJ'),
        ),
        migrations.AlterField(
            model_name='harvest',
            name='year',
            field=models.SmallIntegerField(unique=True, verbose_name='Ano'),
        ),
    ]
