# Generated by Django 5.2.3 on 2025-06-16 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agriculture_api', '0002_alter_farmer_document_alter_harvest_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cultivatedcrop',
            options={'verbose_name': 'Cultivated Crop', 'verbose_name_plural': 'Cultivated Crops'},
        ),
        migrations.AlterUniqueTogether(
            name='cultivatedcrop',
            unique_together={('name', 'harvest')},
        ),
    ]
