# Generated by Django 5.2.3 on 2025-06-16 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriculture_api', '0003_alter_cultivatedcrop_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cultivatedcrop',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='cultivatedcrop',
            constraint=models.UniqueConstraint(fields=('name', 'harvest'), name='unique_cultivated_crop_per_harvest'),
        ),
    ]
