# Generated by Django 5.2.3 on 2025-06-17 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriculture_api', '0004_alter_cultivatedcrop_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harvest',
            name='year',
            field=models.PositiveSmallIntegerField(unique=True, verbose_name='Ano'),
        ),
    ]
