name: Brain Agriculture CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate .env file
        run: |
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> src/.env
          echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> src/.env
          echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> src/.env
          echo "POSTGRES_PORT=${{ secrets.POSTGRES_PORT }}" >> src/.env
          echo "POSTGRES_HOST=${{ secrets.POSTGRES_HOST }}" >> src/.env
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> src/.env
          echo "DEBUG=${{ secrets.DEBUG }}" >> src/.env
          echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> src/.env
          echo "CSRF_TRUSTED_ORIGINS=${{ secrets.CSRF_TRUSTED_ORIGINS }}" >> src/.env
          echo "ALLOWED_HOSTS=${{ secrets.ALLOWED_HOSTS }}" >> src/.env

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker containers
        run: make build

      - name: Run tests
        run: make test
